### ISSUE TITLE
По запросу "ев" находятся "ели".

### ISSUE THREAD

**Issue by un1t** [imotov/elasticsearch-analysis-morphology#19]
Ответ не соотвествует запросу. Почему так?

Маппинг:

            'properties': {
                'id': {'type': 'integer'},
                'name': {'type': 'string', 'analyzer': 'russian_morphology'},
            }

Запрос

    curl -XPOST 'http://localhost:9200/myindex/tags/_search' -d '{"query": 
                               {"match": {"name": "ев"}}}'

Ответ:

    {
        "_shards": {
            "failed": 0,
            "successful": 5,
            "total": 5
        },
        "hits": {
            "hits": [
                {
                    "_id": "1160",
                    "_index": "myindex",
                    "_score": 5.7484603,
                    "_source": {
                        "id": 1160,
                        "name": "ели"
                    },
                    "_type": "tag"
                }
            ],
            "max_score": 5.7484603,
            "total": 1
        },
        "timed_out": false,
        "took": 5
    }

**Comment by imotov** [comment]
Это происходит потому, что оба слова генерируют токен `есть`:

```
curl -XPOST 'http://localhost:9200/myindex/_analyze?field=name&pretty' -d 'ели'
{
  "tokens" : [ {
    "token" : "ель",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "<ALPHANUM>",
    "position" : 1
  }, {
    "token" : "есть",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "<ALPHANUM>",
    "position" : 1
  } ]
}
```

```
curl -XPOST 'http://localhost:9200/myindex/_analyze?field=name&pretty' -d 'ев'    
{
  "tokens" : [ {
    "token" : "ева",
    "start_offset" : 0,
    "end_offset" : 2,
    "type" : "<ALPHANUM>",
    "position" : 1
  }, {
    "token" : "есть",
    "start_offset" : 0,
    "end_offset" : 2,
    "type" : "<ALPHANUM>",
    "position" : 1
  } ]
}
```

Почему это происходит я не уверен. Но я думаю этот вопрос лучше задать в проекте https://github.com/AKuznetsov/russianmorphology

**Comment by un1t** [comment]
Спасибо за ответ. Попробую узнать у них.

**Comment by un1t** [comment]
Если кому интересно, ответ тут
https://github.com/AKuznetsov/russianmorphology/issues/3
