### ISSUE TITLE
URL for 2.X

### ISSUE THREAD

**Issue by Dimutrulkin** [imotov/elasticsearch-analysis-morphology#23]
Hello!
How can we get URL for 2.X version of plugin? When we use
bin/plugin --install imotov/elasticsearch-analysis-morphology
we get error:
Message:
   Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.

**Comment by alehano** [comment]
+1. When will be release for 2.0.0?

**Comment by imotov** [comment]
2.0.0 is released
