### ISSUE TITLE
Failed to find filter russian_morphology

### ISSUE THREAD

**Issue by knownwhat** [imotov/elasticsearch-analysis-morphology#25]
Добрый день! Обнаружил подобную проблему, перерыл все известные форумы. Версия 2.0.1. Использовал Ваш demo.sh Лог прилагаю. Буду благодарен, если подскажите, что не так. Спасибо!

[log.txt](https://github.com/imotov/elasticsearch-analysis-morphology/files/38929/log.txt)

**Comment by imotov** [comment]
Похоже, что плагин не проинсталлировался. Что в логе сервера появляется после его перезагрузки?

**Comment by knownwhat** [comment]
Так. Первое в консоли
/usr/share/elasticsearch/bin/plugin -l
Installed plugins:
    - analysis-morphology
    - kopf
    - mapper-attachments
По логам:
Добавил запись в yml конфига вида
path.logs:   /var/log/ES.log
перезапустил сервер и демку. Записей не появилось. Может не туда смотрю?

**Comment by knownwhat** [comment]
Лог нашел. прикладываю
[elasticsearch.txt](https://github.com/imotov/elasticsearch-analysis-morphology/files/38974/elasticsearch.txt)

**Comment by knownwhat** [comment]
Удалил плагин mapper-attachments, думал из-за него несовместимость. Не помогло. Думаем дальше

**Comment by imotov** [comment]
А можно посмотреть на лог без mapper-attachments

**Comment by knownwhat** [comment]
Да, конечно. Порядок:
1. почистил лог
2. рестартанул сервис
3. лог в студии
[elasticsearch.txt](https://github.com/imotov/elasticsearch-analysis-morphology/files/38991/elasticsearch.txt)

**Comment by imotov** [comment]
Плагин не загрузился:
```
[2015-11-19 17:12:48,533][INFO ][plugins                  ] [Human Top] loaded [], sites [kopf]
                                                                              ^^^^ - тут должен быть  
```
Надо смотреть, что находится в папке plugins.

**Comment by knownwhat** [comment]
Содержимое папки с плагином
![tmp](https://cloud.githubusercontent.com/assets/8859579/11273098/8f732ff2-8ee2-11e5-8f20-3155234ce388.jpg)
![tmp2](https://cloud.githubusercontent.com/assets/8859579/11273099/8f7a7ee2-8ee2-11e5-8d09-61d3c3c21ca5.jpg)

**Comment by imotov** [comment]
Версия плагина не та. Вам нужно поставить 1.2.1 - http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/1.2.1/elasticsearch-analysis-morphology-1.2.1.zip

**Comment by knownwhat** [comment]
Все отлично! Спасибо! Первую страничку лучше поправить. Ибо проблема не у меня одного. Еще раз спасибо!

**Comment by imotov** [comment]
А что не первой страничке не правильно? Вроде все URL правильные в [таблице совместимости](https://github.com/imotov/elasticsearch-analysis-morphology#compatibility).
