### ISSUE TITLE
При использовании wildcard есть слова, которые не находятся

### ISSUE THREAD

**Issue by satabol** [imotov/elasticsearch-analysis-morphology#26]
Здравствуйте, Игорь.

При использовании плагина русской морфологии возникла описанная в **subject** проблема. Вот более подробное описание:
Для поиска полей, заполненных с ошибками, использую **wildcard** символы. Среди прочих примеров, работающих нормально, попались документы "**ЛИИЖТ**" и "**ЛИИЖТ1**". Захотел увидеть эти две записи в одной выборке и задал поиск "_ЛИИЖТ*_", но в результате получил только один документ "**ЛИИЖТ1**". В тоже время, если у меня в базе есть записи "**ИКЕА**" и "**ИКЕА1**", то "_ИКЕА*_" выдаёт оба документа. Затем я поэкспериментировал с "**ЛИИЖТ**" разными способами и выяснил, что такая проблема есть у всех слов/буквосочетаний, которые заканчиваются на "**ЖТ**" (вот выдуманная комбинация пар, которая не находится): 
- два документа (**РАЖТ**, **РАЖТА**)-ищем _РАЖТ*_ - результат только один документ **РАЖТА**
- два документа (**ВЫПУЛЬЖТ**, **ВЫПУЛЬЖТ1**) - ищем _ВЫПУЛЬЖТ*_ - результат только один документ **ВЫПУЛЬЖТ1**
- два документа (**ЖТ**, **ЖТ1**) - ищем _ЖТ*_ - результат только один документ **ЖТ1**

Если маска поиска _ЛИИЖ*_ результаты неправильные.

Если в качестве примера для поиска использовать окончание слова совсем без ЖТ перед * (например, _ЛИИ*_ ), то всё находится нормально.

Если после **ЖТ** что-то написано в обоих случаях, то всё находится:
- два документа (**РАЖТА**, **РАЖТА1**)-ищем _РАЖТА*_ - результат два документ **РАЖТА** и **РАЖТА1**
- два документа (**ВЫПУЛЬЖТА**, **ВЫПУЛЬЖТА1**) - ищем _ВЫПУЛЬЖТ*_ или _ВЫПУЛЬЖТА*__ - результат два документа **ВЫПУЛЬЖТА** и **ВЫПУЛЬЖТА1**
- два документа (**ЖТА** и **ЖТА1**) - поиск _ЖТА*_ - результат два документа (**ЖТА** и **ЖТА1*)

Дополнительно обнаружил, что та же проблема и с этими же буквами при использовании регулярных выражений:
- два документа (**РАЖТ**, **РАЖТА**)-ищем Наименование:_/РАЖТ*/_ - результат только один документ **РАЖТА**

Корректная работа:
- два документа (**ЛИИЖТА**, **ЛИИЖТА1**)-ищем Наименование:_/ЛИИЖТА*/_ - результат два документа **ЛИИЖТА** и **ЛИИЖТА1**

Маппинг для поля (использую русские буквы для имён индексов и типов, проблем не обнаружил):
```javascript
"контрагенты": {
    "ленстрой" : {
        "_all" : {"analyzer" : "russian_morphology", "store" : "true", "index_options": "offsets"},
        "dynamic" : "false", /* Не принимать автоматически новых свойств */
        "properties" : {
                "Наименование"	: {"type" : "string", "index" :     "analyzed", "analyzer" : "russian_morphology", "include_in_all": "true", "store" : "true", "index_options": "offsets", "fields" : { "raw" : {"type" : "string", "index" : "not_analyzed", "include_in_all": "false"}} }, // 
        }
    },
```

```javascript
analyzer: {
    "analyzer" : {
        "default" : {
            "tokenizer" : "standard",
            "filter" : [
                "lowercase",
                'russian_morphology', 'english_morphology'
            ]
        },
    },
    "filter" : {}
}
```
Пример запроса:

```javascript
POST http://serv-japp2.stpr.ru:9200/_search?pretty HTTP/1.1
Host: serv-japp2.stpr.ru:9200

{
    "from" : 0, "size" : 10,
    "query" : {
        "indices" : {
            "indices" : ["контрагенты"],
            "query" : {
                "query_string" : {
                    "fields" : ["Наименование"],
                    "query" : "ЛИИЖТ*",
                    "default_operator" : "and"
                }
            },
            "no_match_query" : "none"
        }
    }
}
```
Пример другого запроса, выдающего аналогичные результаты:

```javascript
POST http://serv-japp2.stpr.ru:9200/_search?pretty HTTP/1.1
Host: serv-japp2.stpr.ru:9200

{
    "from" : 0, "size" : 10,
    "query" : {
                "query_string" : {
                    "fields" : ["Наименование"],
                    "query" : "ЛИИЖТ*",
                    "default_operator" : "and"
                }
            }
}
```
Версии компонентов:
- ElasticSearch - **2.1**
- russian_morphology - **2.1**
- Версия Linux: **oracle linux 6**
- JDK - **1.8.0_66**

**Спасибо**.

**Comment by imotov** [comment]
TL;DR: wildcard с морфологией не дружат - надо пользоваться либо одним, либо другим

Если подробнее, то морфологический анализатор преобразует `ЛИИЖТ` в  `лиить` и  `РАЖТ` в `рать`. В то время как `ЛИИЖТА` и `РАЖТА` остаются неизменными:

```
curl -XGET "localhost:9200/test/_analyze?pretty" -d '{
   "field" : "Наименование",
   "text": "ЛИИЖТА, ЛИИЖТ, ЛИИЖТА1, РАЖТА, РАЖТ"
}'
{
  "tokens" : [ {
    "token" : "лиижта",
    "start_offset" : 0,
    "end_offset" : 6,
    "type" : "<ALPHANUM>",
    "position" : 0
  }, {
    "token" : "лиить",
    "start_offset" : 8,
    "end_offset" : 13,
    "type" : "<ALPHANUM>",
    "position" : 1
  }, {
    "token" : "лиижта1",
    "start_offset" : 15,
    "end_offset" : 22,
    "type" : "<ALPHANUM>",
    "position" : 2
  }, {
    "token" : "ражта",
    "start_offset" : 24,
    "end_offset" : 29,
    "type" : "<ALPHANUM>",
    "position" : 3
  }, {
    "token" : "рать",
    "start_offset" : 31,
    "end_offset" : 35,
    "type" : "<ALPHANUM>",
    "position" : 4
  } ]
}
```
Другими словами анализатор ожидает полное слово и обрабатывает его как полное слово. Поэтому поиск по подстроке в этом сценарии просто не уместен.

**Comment by satabol** [comment]
Игорь, спасибо за "_analize" - не знал про него.
Но что вы имеете в виду под "надо пользоваться либо одним, либо другим"? Могу ли я в одном поле "объявить" два типа, например с помощью "fields" и задать им два способа обработки - один способ - индексировать, а второй - raw - не индексировать, например, так:
```javascript
"Наименование" : {"type" : "string", "index" : "analyzed", "analyzer" : "russian_morphology", "include_in_all":  "true", "store" : "true", "index_options": "offsets", 
"fields" : { "raw" : {"type" : "string", "index" : "not_analyzed", "include_in_all": "false"}} }
```

Немного экспериментов:

Проверил такой fields и поиск query по Наименование.raw:"__ЛИИЖТ*__" не находит вообще ничего, а если ищу "__ЛИИЖТ__" без wildcard находит только ЛИИЖТ. И, соответственно, если ищу Наименование.raw:"__ЛИИЖТ1__", то ЛИИЖТ1 находит.

Ещё такой метод поиска:
```javascript
POST http://serv-japp2.stpr.ru:9200/_search?pretty HTTP/1.1
Host: serv-japp2.stpr.ru:9200

{
    "from" : 0, "size" : 10,
    "query" : {
                    "wildcard" : { "Наименование.raw" : { "value" :  "ЛИИЖТ*"}}
    }
}
```
В этом случае, находятся все желаемые записи, но мне этот метод не подходит.

Можно ли получить нужный результат через mapping fields?

**Comment by imotov** [comment]
Я не очень понял из вашего описания в чем проблема, но поскольку ваша ситуация не является описанием бага морфологического анализатора, я бы предложил продолжить данную дискуссию на https://discuss.elastic.co/c/in-your-native-tongue/15-category Вы не могли бы задать этот вопрос там и при этом приложить скрипт, который полностью воспроизводил бы проблему.

**Comment by satabol** [comment]
Спасибо за ссылку. Не знал про неё.
