### ISSUE TITLE
Elasticsearch 2.1.2 Support

### ISSUE THREAD

**Issue by kimrgrey** [imotov/elasticsearch-analysis-morphology#29]
ElasticSearch 2.1.2 has been released. This release contains some bug fixes. I'm not sure, but don't think that plugin should be changed in some way to make new release. Isn't it?

**Comment by imotov** [comment]
No, starting with 2.0.0 each plugin has to indicate the version of elasticsearch that it is targeting. So, even though nothing has changed in the plugin itself, you need to install the new version of the plugin that would match the corresponding version of elasticsearch.

**Comment by kimrgrey** [comment]
Yep, I understand it. But there is no release for 2.1.2 here: https://github.com/imotov/elasticsearch-analysis-morphology/releases. So, if plugin doesn't need changed to support ES 2.1.2 may be you can create appropriate version of the package? I would be awesome! =)

**Comment by kimrgrey** [comment]
Oh, you have created it! Thank you very much!
