### ISSUE TITLE
Elasticsearch 2.2.0 (IndexCreationException)

### ISSUE THREAD

**Issue by kostya-ten** [imotov/elasticsearch-analysis-morphology#30]
Возникает такая ошибка при запуске demo.sh

{"error":"IndexCreationException[[rustest] failed to create index]; nested: IllegalArgumentException[Custom Analyzer [my_analyzer] failed to find filter under name [russian_morphology]]; ","status":400}

Устанавливал так
`/usr/share/elasticsearch/bin/plugin install http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/2.2.0/elasticsearch-analysis-morphology-2.2.0.zip`

Указанно что модуль установлен.
`/usr/share/elasticsearch/bin/plugin list`

**Installed plugins in /usr/share/elasticsearch/plugins:
    - elasticsearch-analysis-morphology**

`dpkg -l | elasticsearch`

ii  elasticsearch                    2.2.0                            all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html

Что делаю не так?

**Comment by imotov** [comment]
@kostya-ten Сколько нод в кластере?  Плагин на всех нодах присутствует? После установки плагина ноды перезапускали? Что в логах?

**Comment by kostya-ten** [comment]
Да, просто один сервер.

[elasticsearch.txt](https://github.com/imotov/elasticsearch-analysis-morphology/files/171904/elasticsearch.txt)

**Comment by imotov** [comment]
> Да, просто один сервер.

Странно. А судя по логу, этот сервер слушает на 9201 порту
```
[2016-03-14 12:15:21,558][INFO ][http                     ] [Mordred] publish_address {127.0.0.1:9201}, bound_addresses {127.0.0.1:9201}, {[::1]:9201}
```

А тест в demo.sh посылает запросы на порт 9200 и судя по тому, что вы получаете ответы с порта 9200, у вас как минимум два сервера на этой машине, и похоже, что сервер на 9200 имеет несовместимую с 2.2.0 версию и поэтому не сформировал кластер с сервером на 9201. 

Для того, чтобы посмотреть на все процессы elasticsearch на этой машине, запустите
```
ps -aef | grep elasticsearch 
```

Для того чтобы посмотреть из каких машин состоит каждый кластер запустите 

```
curl -s "localhost:9200/_cat/nodes?v&h=pid,host,port"
curl -s "localhost:9201/_cat/nodes?v&h=pid,host,port"
```

Для того, что бы demo.sh заработал, вам надо установить плагин на сервер, который работает на порту 9200, или изменить порт в скрипте на тот порт, на котором ваш сервер работает.

**Comment by kostya-ten** [comment]
Вы гений, бага в самом эластике. При обновление с 2.0.0 до 2.2.0 осталось копия эластика, он её не проверял и не убивал при обновление пакета.
