### ISSUE TITLE
как правильно задать одновременно английскую и русскую морфологию?

### ISSUE THREAD

**Issue by danilvoe** [imotov/elasticsearch-analysis-morphology#31]
Как правильно оформить конфиг?

**Comment by imotov** [comment]
Что значит "оформить конфиг"?

**Comment by danilvoe** [comment]
Брал конфиг для elasticsearch  вот от сюда - https://github.com/asyncee/elasticsearch-russian-config/tree/master/config

Как я понял там упор сделаны на русскую морфологию, как туда задавить

**Comment by danilvoe** [comment]
Извините...
Как добавить туда анализ английских слов? Например сочитание ArhiveOTI воспринимается целиком как слово и при поиске просто по OTI не находится.

**Comment by imotov** [comment]
По идее должно работать. Но, возможно, вы схему неправильно задали или ищете фильтрами без анализатора. Вы не могли бы показать полный пример с тем как индекс создаете, документом, который вы добавляете, как ищите и что получаете. Но похоже, что этот вопрос к плагину русской морфологии отношения не имеет. Поэтому лучше этот вопрос задать на форуме для вопросов об Elasticsearch на русском языке https://discuss.elastic.co/c/in-your-native-tongue/15-category Я там не него отвечу.
