### ISSUE TITLE
Elasticsearch 2.4.1 support

### ISSUE THREAD

**Issue by knownwhat** [imotov/elasticsearch-analysis-morphology#36]
Can you please release version for Elasticsearch 2.4.1?

And why every minor elasticsearch version requires new version of plugin? Is backwards compatibility possible at all? May be I can install 2.4.0 plugins version to elasticsearch 2.4.1 somehow?

Thank you.

**Comment by knownwhat** [comment]
Еще раз добрый день! Очень прошу выпустить обновление, часть индексов после рестарта эластика просто не запускается выдавая сообщение 
"details": "failed to create index, failure IndexCreationException[failed to create index]; nested: IllegalArgumentException[Custom Analyzer [FIO] failed to find filter under name [russian_morphology]]; "

**Comment by imotov** [comment]
Missed 2.4.1 somehow. Released.

**Comment by knownwhat** [comment]
Дружище, спасибо!
