### ISSUE TITLE
search issue "Япония"

### ISSUE THREAD

**Issue by andreyponteleev** [imotov/elasticsearch-analysis-morphology#39]
how must we search for finding 4,5,6 from demo script? https://github.com/imotov/elasticsearch-analysis-morphology/blob/master/demo.sh

**Comment by imotov** [comment]
All Russian language stemmers that I know (including this one) treat Russian nouns and adjectives with the same stem as two different words. You would need to develop (or find) a more aggressive stemmer that wouldn't do that or use some other approach (n-grams, fuzzy matching, etc.).
