### ISSUE TITLE
Разрешение омонимии

### ISSUE THREAD

**Issue by wingrime** [imotov/elasticsearch-analysis-morphology#45]
в текущей реализации генерируются токены всех возможных вариантов,  Есть ли возможность разрешения омонимии? хотя-бы статистическими методами

**Comment by imotov** [comment]
Этот анализатор работает на уровне одного слова. У него полностью отсутсвует контекст.  Что вы понимаете под статистическими методами?

**Comment by wingrime** [comment]
pymorphy использует статистику употребления в корпусе, что бы ранжировать словоформы. Данный анализатор выдает все словоформы, что создаёт проблемы например Уже -> узкий.

Хотелось бы иметь возможность использовать только самую частотную форму, либо отсекать по частотности.
