### ISSUE TITLE
Can't install plugin on elasticsearch 5.6.5

### ISSUE THREAD

**Issue by antonshell** [imotov/elasticsearch-analysis-morphology#48]
Hello!

Trying to install plugin on elasticsearch 5.6.5
When try to use russian_morphology get such error.

```
failed to find global analyzer [russian_morphology]
```

**Steps to reproduce**

1 . Run elasticsearch in docker

```
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:5.6.5
```

2 . Login to docker image

```
docker exec -it elasticsearch5 bash
```

3 . Install Plugin

```
bin/elasticsearch-plugin install http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.5/elasticsearch-analysis-morphology-5.6.5.zip
```
4 . Ensure plugin is installed

```
bin/elasticsearch-plugin list
```
analysis-morphology

5. Try to use analyzer

```
curl -X POST \
  http://localhost:9200/_analyze \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 1a4b60b6-7d0d-5962-63c3-1bf0005e2012' \
  -d '{
  "analyzer" : "russian_morphology",
  "text" : "Стандартный анализатор разбил строку по пробелам и перевел все в нижний регистр, анализатор russian — убрал не значимые слова, перевел в нижний регистр и оставил основу слов."
}'
```
See such responce:

```
{
    "error": {
        "root_cause": [
            {
                "type": "remote_transport_exception",
                "reason": "[oGrvxj7][127.0.0.1:9300][indices:admin/analyze[s]]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "failed to find global analyzer [russian_morphology]"
    },
    "status": 400
}
```

Have similar issue when creating index, as described here:
https://github.com/imotov/elasticsearch-analysis-morphology/blob/master/demo.sh

6. Tried restart elastic search. Same result

```
apt-get update
apt-get install -y procps
service elasticsearch restart
```

Log content:
/var/log/elasticsearch/elasticsearch.log

[elasticsearch.log](https://github.com/imotov/elasticsearch-analysis-morphology/files/1638575/elasticsearch.log)

PS. I have seen this issue, it seems similar, but I can't figure it out.
As i see, I use correct version of plugin

https://github.com/imotov/elasticsearch-analysis-morphology/issues/25

**Comment by imotov** [comment]
The simplest way to solve this issue would be to install the plugin before starting elasticsearch by extending the standard image. You can do that by adding `RUN elasticsearch-plugin ...` command to the Dockerfile and then building the image. Something like this should do the trick

```
FROM docker.elastic.co/elasticsearch/elasticsearch-platinum:5.6.5

RUN elasticsearch-plugin install http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.5/elasticsearch-analysis-morphology-5.6.5.zip
```

See [this blog post](https://www.elastic.co/blog/elasticsearch-docker-plugin-management) for a more detailed explanation.

Since it's not really a elasticsearch-analysis-morphology bug I am going to close this issue.

**Comment by antonshell** [comment]
It works, thank you!
