### ISSUE TITLE
Letters "е" and "ё" is not equals.

### ISSUE THREAD

**Issue by snikulitsa** [imotov/elasticsearch-analysis-morphology#55]
Elasticsearch version 5.6.11
In Elasticsearch 2.4.4 problem does not exist.

**Comment by imotov** [comment]
I am not really sure what you mean. Could you show an example that works in 2.4.4 and doesn't in 5.6.11?

**Comment by snikulitsa** [comment]
Sorry, in elasticsearch 2.4.4 the problem also exists.

I have index with mapping:
`{
  "testindex": {
    "mappings": {
      "document": {
        "properties": {
          "content": {
            "type": "string",
            "store": true,
            "analyzer": "russian_morphology"
          },
          "title": {
            "type": "string",
            "store": true,
            "analyzer": "russian_morphology"
          }
        }
      }
    }
  }
}`

One document in index:
`{
          "title": "Заголовок",
          "content": "ёжик заблудился в лесу"
 }`

I'm try to serch:
`{
  "query": {
    "match": {
      "content": {
        "query": "ежик",
        "type": "boolean"
      }
    }
  }
}`

result is:
`  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }`


But here https://github.com/AKuznetsov/russianmorphology  in readme "It assume what letters е and ё are the same."


If I try to search:
`{
  "query": {
    "match": {
      "content": {
        "query": "ёжик",
        "type": "boolean"
      }
    }
  }
}`

result is:
`  "hits": {
    "total": 1,
    "max_score": 0.15342641,
    "hits": [
      {
        "_index": "testindex",
        "_type": "document",
        "_id": "AWZc9iWb1VQpEckmGRXZ",
        "_score": 0.15342641,
        "_source": {
          "title": "Заголовок",
          "content": "ёжик заблудился в лесу"
        }
      }
    ]
  }`

**Comment by imotov** [comment]
The fact that it treats both the same way doesn't mean that it replaces one with another:

```
GET testindex/_analyze
{
  "field": "content",
  "text": "ёжик"
}
{
  "tokens": [
    {
      "token": "ёжик",
      "start_offset": 0,
      "end_offset": 4,
      "type": "<ALPHANUM>",
      "position": 0
    }
  ]
}
GET test/_analyze
{
  "field": "content",
  "text": "eжик"
}
{
  "tokens": [
    {
      "token": "eжик",
      "start_offset": 0,
      "end_offset": 4,
      "type": "<ALPHANUM>",
      "position": 0
    }
  ]
}
```
If you want them to be converted to the same letter, you can a [mapping char filter](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/analysis-mapping-charfilter.html).
