### ISSUE TITLE
Build issue - cannot resolve org.apache.lucene.morphology:*:*-SNAPSHOT

### ISSUE THREAD

**Issue by ov7a** [imotov/elasticsearch-analysis-morphology#61]
Subj. Tried to build plugin from sources but packages
```
org.apache.lucene.morphology:russian:1.3-SNAPSHOT
org.apache.lucene.morphology:english:1.3-SNAPSHOT
org.apache.lucene.morphology:morph:1.3-SNAPSHOT
```
are nowhere to be found. Same goes for `1.4-SNAPSHOT` Where can they be downloaded from?

**Comment by imotov** [comment]
As you can see in https://github.com/AKuznetsov/russianmorphology/issues/17 the upstream project stopped releasing the them. So you have to build them yourself from sources.

**Comment by ov7a** [comment]
Thanks. It would be nice if it has been explicitly stated in README.

**Comment by imotov** [comment]
>  It would be nice if it has been explicitly stated in README.

I agree. Do you want to open a PR for that?

**Comment by ov7a** [comment]
On second thought, may be it would be better to make use of @babayotakun work and fix the build, like @xumix did in [his fork](https://github.com/xumix/elasticsearch-analysis-morphology)?

**Comment by imotov** [comment]
Unfortunately, I don't really know neither of them, which makes me somewhat uneasy to download their binaries nor promote these binaries here.

**Comment by xumix** [comment]
@ov7a I've used @babayotakun work and just fixed the build, if you don't trust my binaries - you can build them yourself
