### ISSUE TITLE
elasticsearch-analysis-morphology-5.6.16.zip not found

### ISSUE THREAD

**Issue by web-premier** [imotov/elasticsearch-analysis-morphology#65]
Hello!
I have error when download plugin by link http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.16/elasticsearch-analysis-morphology-5.6.16.zip
Where I can get it?

**Comment by imotov** [comment]
Duplicate of #64

**Comment by imotov** [comment]
I have updated the readme with the building from source instructions.
